
language: cpp
compiler: gcc
dist: trusty

notifications:
  email: false

sudo: false

os: linux

branches:
  only:
  - master

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script:
  - make help
  - echo "ECHO_FLAG:=" >> config/dubug
  - travis_wait 30 make all
  - make unittest
  
