
language: cpp

notifications:
  email: false

sudo: false

os: linux

addons:
  packages:
    - g++-6

script:
  - make help
  - echo "CXX:= g++-6" >> config/debug
  - make all
  - make unittests
  
  
